[
  {
    "details": {
      "PatientName": "rajesh",
      "patientLocation": [
        {
          "temparoryLoc": "mumbai",
          "Location": {
            "State": "telangana",
            "City": "warangal",
            "House number": "12-76-88"
          }
        }
      ],
      "Citizen": "india",
      "PatientAddressdetails": {
        "patientaddress": {
          "addressdetails": "Hyderabad, H.no 1-80, village Ladak",
          "permanentdetails": "Hyderabad Kondapur 50532 House"
        }
      },
      "hospitalName": "Yashoda",
      "ZIPCODE": [
        {
          "temparoryLocZip": "78787",
          "ZipCode": "505320"
        }
      ]
    },
    "Age": "22",
    "Govtid": "123455",
    "Categerie": {
      "gender": "male"
    }
  }
]